### ISSUE TITLE
Feedback on Milestone 2

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Vancouver_Bike_Theft_Analysis#22]
@Jamienie and @makka3, great job on Milestone 2! All I can add is the following:

- [ ] Table 1 in the report appears as a code snippet rather than a rendered table.
- [ ] I see that you have addressed almost all feedback noted for Milestone 1, so do not forget to close the issue on Github :)   

**Suggestions:**

- Go through http://swcarpentry.github.io/make-novice/reference. This would help you make your Make code more practical. For example, you can use automatic variables and avoid some repetition.

**Comment by makka3** [comment]
Thank you Ozum for your constructive feedback throughout the project. We made the following changes to address your suggestions and fulfill the requirements of the final project:
- Rendered the table in the final report and made formatting edits
- Making and documenting the Docker file
- Added a Code of Conduct
- Edited the Readme to account for Docker file instructions
- Closing all the issues

We looked into making our code more practical using the link above, but ultimately made little to no changes in the project for the purposes of time. We will definitely be considering this when implementing future projects. 

Hope you enjoy/enjoyed reading our project, and thank you once again for all of your suggestions.

-Makk and Fan
